### ISSUE TITLE
Sunrise/Sunset

### ISSUE THREAD

**Issue by macjeff** [exking/udi-sun-poly#1]
Someone suggested I ask you for new data in your server or to hire you to help.  I need to place TOMORROW sunrise into ISY for my location.  The ISY gives you today sunrise but even at 3pm it shows you todays not tomorrows.   I use the TimeData node to put in the Month and stuff into the email and can put todays sunrise via ISY but cant get tomorrows.  

Can you help?  You can PM me if you want.

**Comment by exking** [comment]
Replied on UDI forum...
